### ISSUE TITLE
[1pt] Create app and install basic dependencies - Setup (group task)

### ISSUE THREAD

**Issue by lucas-crodrigues** [lucas-crodrigues/space-trav-hub#24]
- Create React App.
- Install [React Redux](https://react-redux.js.org/), [Redux Logger](https://www.npmjs.com/package/redux-logger) and [React Router](https://reactrouter.com/web/guides/quick-start).

**Comment by mukhammadrizooff** [comment]
Hi @TEAM, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

<img src="https://media3.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Suggested changes
- [ ] [REQUIRED] You should paste a link to your GitHub project in your issue's description.
- [ ] [REQUIRED] Please add a note about how many people there are on your team.

![image](https://user-images.githubusercontent.com/63915024/185965274-b1f5ba0f-546d-4fa6-aa8b-a9ad19c530c3.png)

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by lucas-crodrigues** [comment]
Sorry @mukhammadrizooff, we'll read the instructions more carefully next time 😅
