### ISSUE TITLE
Setup kanban board

### ISSUE THREAD

**Issue by lucas-crodrigues** [lucas-crodrigues/space-trav-hub#25]
https://github.com/lucas-crodrigues/space-thub
We're working in a group of two people, myself (@lucas-crodrigues) and @aizjicod

**Comment by dasileker** [comment]
### **Hi @lucas-crodrigues,** 

### **Great work on making the changes 👏** 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## **Suggested changes**
_Check the comments under the review._

- `You should add the link for the **repo/projects**, please do so and ask for a review, and also please use the same issue and do not create another issue for review.`


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by lucas-crodrigues** [comment]
All right @dasileker, we are terribly sorry for that, here is the correct link: https://github.com/lucas-crodrigues/space-trav-hub/projects/1

**Comment by julie-ify** [comment]
Hi @lucas-crodrigues and @aizjicod,

## Highlights!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by lucas-crodrigues** [comment]
Thank you @julie-ify and @dasileker
